I'm sorry, but an uncaught exception occurred.

While running game code:
OSError: [Errno 2] No such file or directory: "/Users/cdean248345/Documents/GitHub/Untitled/Ren'Py Translator ToolKit-bb60a30c13/game/saves/persistent"

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/Users/cdean248345/renpy-7.4.11-sdk/renpy/bootstrap.py", line 331, in bootstrap
    renpy.main.main()
  File "/Users/cdean248345/renpy-7.4.11-sdk/renpy/main.py", line 665, in main
    renpy.persistent.update(True)
  File "/Users/cdean248345/renpy-7.4.11-sdk/renpy/persistent.py", line 395, in update
    save()
  File "/Users/cdean248345/renpy-7.4.11-sdk/renpy/persistent.py", line 411, in save
    renpy.loadsave.location.save_persistent(data)
  File "/Users/cdean248345/renpy-7.4.11-sdk/renpy/savelocation.py", line 496, in save_persistent
    l.save_persistent(data)
  File "/Users/cdean248345/renpy-7.4.11-sdk/renpy/savelocation.py", line 354, in save_persistent
    self.persistent_mtime = os.path.getmtime(fn)
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/genericpath.py", line 62, in getmtime
OSError: [Errno 2] No such file or directory: "/Users/cdean248345/Documents/GitHub/Untitled/Ren'Py Translator ToolKit-bb60a30c13/game/saves/persistent"

Darwin-21.4.0-x86_64-i386-64bit
Ren'Py 7.4.11.2266
Ren'Py Translator ToolKit 1.8
Wed May 18 15:20:47 2022
